import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import QRCode from 'qrcode.react';
// import { getBalance, payInvoice, createInvoice } from './lightning/lnd-webln';
// import { getBalance, createInvoice, payInvoice } from "@/lightning/lnd-rest"
import { getBalance, createInvoice, payInvoice } from "@/lightning/lnd-grpc"

function SendModal({ onClose }) {
  const [invoice, setInvoice] = useState('');
  const [paymentMessage, setPaymentMessage] = useState('');

  const handleSubmit = async (event) => {
    event.preventDefault();
    
    const result = await payInvoice(invoice);

    if (result || !result?.message === "Error fetching data") {
      setPaymentMessage("Payment successful!");
      setInvoice('');
    } else {
      setPaymentMessage('Payment failed...');
    }
  };

  return (
    <div className={styles.modal}>
      <h2>Send Invoice</h2>
      <form onSubmit={handleSubmit}>
        <label>Invoice:</label>
        <br />
        <input type="text" value={invoice} onChange={e => setInvoice(e.target.value)} />
        <br />
        <button className={styles.button} type="submit">Submit</button>
      </form>
      <button className={styles.button} onClick={onClose}>Close</button>
      {paymentMessage && <p>{paymentMessage}</p>}
    </div>
  );
}

function ReceiveModal({ onClose }) {
  const [amount, setAmount] = useState('');
  const [invoice, setInvoice] = useState('');
  const [message, setMessage] = useState('');
  
  const handleSubmit = async (event) => {
    event.preventDefault();
    const paymentRequest = await createInvoice(amount);
    if (paymentRequest) {
      setInvoice(paymentRequest);
      setMessage('Invoice created successfully.');
    } else {
      setMessage('Error creating invoice.');
    }
  };

  return (
    <div className={styles.modal}>
      <h2>Receive Amount</h2>
      <form onSubmit={handleSubmit}>
        <label>Amount:</label>
        <br />
        <input type="number" value={amount} onChange={e => setAmount(e.target.value)} />
        <br />
        <button className={styles.button} type="submit">Submit</button>
      </form>
      <button className={styles.button} onClick={onClose}>Close</button>
      {invoice ? (
        <>
          <p>{message}</p>
          <QRCode value={invoice} size={256} level="H" />
          <br />
          <span>Invoice:</span>
          <br />
          <span>{invoice}</span>
        </>
      ) : (
        <p>{message}</p>
      )}
    </div>
  );
}

export default function Home() {
  const [showSendModal, setShowSendModal] = useState(false);
  const [showReceiveModal, setShowReceiveModal] = useState(false);
  const [balance, setBalance] = useState(null);

  const fetchBalance = async () => {
    const balanceResult = await getBalance();
    if (balanceResult) {
      console.log('Balance fetched successfully', balanceResult);
      setBalance(balanceResult?.balance);
    } else {
      console.error('Failed to fetch balance');
    }
  };

  useEffect(() => {
    if (!balance) fetchBalance();
  }, [balance]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>Balance: {balance}</h3>
        <div className={styles.buttonRow}>
          <button className={styles.button} onClick={() => setShowSendModal(true)}>Send</button>
          <button className={styles.button} onClick={() => setShowReceiveModal(true)}>Receive</button>
        </div>
        {showSendModal && <SendModal onClose={() => setShowSendModal(false)} styles={styles} />}
        {showReceiveModal && <ReceiveModal onClose={() => setShowReceiveModal(false)} styles={styles} />}
      </main>
    </>
  )
}
